import Providers from "./Providers";
import ToggleThemeButton from "./components/buttons/ToggleThemeButton";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#f5f5f5] dark:bg-[#191919] min-h-screen">
        <Providers>
          <ToggleThemeButton />
          {children}
        </Providers>
      </body>
    </html>
  );
}
