import type { Metadata } from "next";
import Header from "./components/organisms/header/header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Najmul Huda Chowdhury | Meta certified professional web developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Header /> {children}
      </body>
    </html>
  );
}
